---
- hosts: all
  become: yes
  tasks:

  - name: Install qemu guest agent using APT
    ansible.builtin.apt:
      name: qemu-guest-agent
      update_cache: yes
      state: latest
    when: ( ansible_distribution == "Debian" ) or 
          ( ansible_distribution == "Ubuntu" )

  - name: Install qemu guest agent using DNF
    ansible.builtin.dnf:
      name: qemu-guest-agent
      update_cache: yes
      state: latest
    when: ( ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "CentOS" and ansible_distribution_major_version >= "9" ) or
          ( ansible_distribution == "Fedora" )
...