---
# ansible-playbook -K -i hosts -l test shutdown-machines.yaml
- hosts: all
  become: yes
  tasks:

  - name: Unconditionally shut down the machine with all defaults
    community.general.shutdown:
...